Create git commands
showmic09/MECH-892 pull request #17
Opened 2024-06-20 16:37 UTC by oliva90

this is homework number 2

2024-06-20 20:20 UTC, showmic09 reviewed
@oliva90 Please change the directory name. You have `OlivaHW2` as the folder name. Moreover, this is not the correct homework. I asked for shell commands like: ls, cd, pwd.

2024-06-20 20:21 UTC, showmic09 requested changes
Also please make them as a bullet list.

2024-06-25 15:07 UTC, oliva90 commented on olivaHW2/HW2/git commands
how do I change the name

2024-06-25 16:29 UTC, showmic09 approved these changes
LGTM

2024-06-25 16:30 UTC, merged