HW-2: shell-loop.sh script to echo numbers from 0 to 9
showmic09/MECH-892 pull request #26
Opened 2024-06-25 16:48 UTC by maksudatoma

2nd part of HW2

2024-06-25 20:03 UTC, showmic09 requested changes
@maksudatoma Please add the file inside your directory. So from the terminal move the file to Toma/HW2. Make sure that you are on the HW2-Toma-patch01 branch and do the following
- git add <filename> and afterwards
- git commit -m "Changed the file's location" and finally
- git push origin HW2-Toma-patch01

2024-06-26 19:55 UTC, maksudatoma commented
@showmic09 I have changed the file's location.

2024-06-26 19:55 UTC, showmic09 requested changes
Hi @maksudatoma if you look under Files changed you will see that you have two files. Can you please delete the other file that's not in the folder. If you want you can use GitHub website for this. otherwise the command from terminal is 
- git rm `<file name>`

2024-06-26 19:58 UTC, showmic09 commented on shell-loop.sh
> +#!/bin/bash
Please delete this file.

2024-06-26 19:58 UTC, showmic09 commented on shell-loop.sh
Please delete this file @maksudatoma

2024-06-26 19:59 UTC, showmic09 approved these changes

2024-06-26 19:59 UTC, showmic09 commented on shell-loop.sh
LGTM now. Thanks

2024-06-26 20:00 UTC, merged