created HW3
showmic09/MECH-892 pull request #54
Opened 2024-07-14 04:36 UTC by nickytagoe

2024-07-14 05:57 UTC, showmic09 requested changes
Hi @nickytagoe, 
Can you please add the result files with this push? I mean 'spill0.error, spill0.out.....' and the other files

2024-07-14 16:16 UTC, nickytagoe commented
> Hi @nickytagoe, Can you please add the result files with this push? I mean 'spill0.error, spill0.out.....' and the other files

Hello Dr. @showmic09  please I have submitted the changes. Thank you

2024-07-14 16:51 UTC, showmic09 commented on Nicky/HW3/R_OSPool.submit
> +output = output/spill$(Process).out
Hi @nickytagoe, please change the output and error location to *errout* as mentioned in the HW3. Just make changes here..you don't need to run the calculations again.

2024-07-15 01:23 UTC, showmic09 approved these changes
LGTM. Good work @nickytagoe

2024-07-15 01:23 UTC, merged